# Generated by Django 4.2.5 on 2024-03-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='loyal_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
